package http;

public enum Endpoint {
    GET_SIMPLETASK_BY_ID,
    GET_SUBTASK_BY_ID,
    GET_EPIC_BY_ID,
    GET_SIMPLETASKS,
    GET_SUBTASKS,
    GET_EPICS,
    GET_ALL_TASKS,
    POST_SIMPLE_TASK,
    POST_SUBTASK,
    POST_EPIC,
    DELETE_SIMPLE_TASK,
    DELETE_SUBTASK,
    DELETE_EPIC,
    DELETE_ALL_TASKS,
    DELETE_SIMPLETASKS,
    DELETE_SUBTASKS,
    DELETE_EPICS,
    GET_EPIC_SUBTASKS,
    GET_HISTORY,
    UNKNOWN
}
